### ISSUE TITLE
Copy the libraries to System32 I think Fatal Error Future

### ISSUE THREAD

**Issue by cheddad2018** [Laex/Delphi-OpenCV#121]
I've built me a program that install the components  auto 
ffmpeg and opengl 
and copy all dll for system 32 and system 64   
To make it easy to live for all developer 
but win 7 ,8, 10 Do not allow copying files to "system32" It is forbidden
Even with admin 'root' access 
Is it possible to create an alternate folder  
And create key  in the registry
تحيا الجزائر

**Comment by checkdigits** [comment]
This is not something you should be doing. 

Installing ‘shared’ components requires you to understand a number of subtle things about installers - for example version control and correct registration of the components in the system’s manifest. You also need to handle correct uninstallation of the shared components too.

Proper installation is not just a matter of editing registry settings. 😀

Rather than do this yourself I’d recommend a dedicated install program such as InnoSetup. InnoSetup is excellent, open source, easy to understand and widely used. There are plenty of others available too so you don’t have to reinvent everything.

**Comment by Laex** [comment]
All necessary dll can be copied to the same directory where your program is located

**Comment by cheddad2018** [comment]
But it is annoying for the developer to do this every time the program builds
Library names are similar   ..... ْ32-bit and 64-bit libraries 
This creates a problem

**Comment by Laex** [comment]
The program is developed for either 32 bits or 64 bits.
There are always difficulties ...

**Comment by cheddad2018** [comment]
thanks Laex  and checkdigits
Can you build a cv applications for Android and ios ... multi-device app
it will be great
